import { GpioDevice } from './gpioCommon';


/**
   * Define two fixed GPIO input devices as contact sensors
   */
export const exampleDevices: GpioDevice[] = [
  {
    group: 'group1',
    pin: 538,
    direction: 'in',
    bcmPort: 'GPIO26',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group1',
    pin: 531,
    direction: 'in',
    bcmPort: 'GPIO19',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group2',
    pin: 525,
    direction: 'in',
    bcmPort: 'GPIO13',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group3',
    pin: 518,
    direction: 'in',
    bcmPort: 'GPIO6',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group3',
    pin: 517,
    direction: 'in',
    bcmPort: 'GPIO5',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group3',
    pin: 512,
    direction: 'in',
    bcmPort: 'GPIO0',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group3',
    pin: 523,
    direction: 'in',
    bcmPort: 'GPIO11',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group3',
    pin: 521,
    direction: 'in',
    bcmPort: 'GPIO9',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group3',
    pin: 522,
    direction: 'in',
    bcmPort: 'GPIO10',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group3',
    pin: 534,
    direction: 'in',
    bcmPort: 'GPIO22',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group3',
    pin: 539,
    direction: 'in',
    bcmPort: 'GPIO27',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group4',
    pin: 529,
    direction: 'in',
    bcmPort: 'GPIO17',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group4',
    pin: 516,
    direction: 'in',
    bcmPort: 'GPIO4',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group4',
    pin: 515,
    direction: 'in',
    bcmPort: 'GPIO3',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group4',
    pin: 514,
    direction: 'in',
    bcmPort: 'GPIO2',
    invertState: false,
    debounceMs: 250,
  },
  {
    group: 'group1',
    pin: 533,
    direction: 'out',
    bcmPort: 'GPIO21',
    invertState: false,
    debounceMs: 100,
  },
  {
    group: 'group2',
    pin: 532,
    direction: 'out',
    bcmPort: 'GPIO20',
    invertState: false,
    debounceMs: 100,
  },
  {
    group: 'group3',
    pin: 528,
    direction: 'out',
    bcmPort: 'GPIO16',
    invertState: false,
    debounceMs: 100,
  },
  {
    group: 'group4',
    pin: 524,
    direction: 'out',
    bcmPort: 'GPIO12',
    invertState: false,
    debounceMs: 100,
  },
];